images:
  app1:
    v1:
      version: "{{ .Version }}-{{ .Parent.Name }}{{ .Parent.Version }}"
      registry: registry.stevedore.test
      builder:
        driver: docker
        options:
          context:
            - path: images-src/app1
      parents:
        busybox:
          - "1.35"
