version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go mod tidy
builds:
  - id: stevedore
    binary: stevedore
    main: ./cmd/stevedore.go
    ldflags: -s -w -X github.com/gostevedore/stevedore/internal/core/domain/release.BuildDate={{.Date}} -X github.com/gostevedore/stevedore/internal/core/domain/release.Version={{ .Version }} -X github.com/gostevedore/stevedore/internal/core/domain/release.Commit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'

archives:
  - id: stevedore
    builds:
      - stevedore
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{.Version}}_
      {{- if eq .Os "linux" }}Linux
      {{- else if eq .Os "darwin" }}Darwin
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'
snapshot:
  name_template: '{{ .ShortCommit }}'
changelog:
  # Set it to true if you wish to skip the changelog generation.
  # This may result in an empty release notes on GitHub/GitLab/Gitea.
  disable: true

