images:
  app1:
    "0.1.0":
      # name: "{{ .Name }}"
      version: "{{ .Version }}-{{ .Parent.Name }}{{ .Parent.Version }}"
      registry: registry.stevedore.test
      builder:
        driver: docker
        options:
          context:
            - path: images-src/app1
      parents:
        base:
          - "2.4.6"
