#!/bin/sh
set -e

ALPINE_VERSION=3.16
UBUNTU_VERSION=20.04

_pull_and_tag_alpine() {
    docker pull alpine:${ALPINE_VERSION}
    docker tag alpine:${ALPINE_VERSION} docker-hub.stevedore.test:5000/library/alpine:${ALPINE_VERSION}
    docker push docker-hub.stevedore.test:5000/library/alpine:${ALPINE_VERSION}
}

_pull_and_tag_busybox() {
    docker pull busybox
    docker tag busybox docker-hub.stevedore.test:5000/library/busybox
    docker push docker-hub.stevedore.test:5000/library/busybox
}

_pull_and_tag_ubuntu_version() {
    docker pull ubuntu:${UBUNTU_VERSION}
    docker tag ubuntu:${UBUNTU_VERSION} docker-hub.stevedore.test:5000/library/ubuntu:${UBUNTU_VERSION}
    docker push docker-hub.stevedore.test:5000/library/ubuntu:${UBUNTU_VERSION}
}

_pull_and_tag_ubuntu_latest() {
    docker pull ubuntu:latest
    docker tag ubuntu:latest docker-hub.stevedore.test:5000/library/ubuntu:latest
    docker push docker-hub.stevedore.test:5000/library/ubuntu:latest
}

_pull_and_tag_alpine &
_pull_and_tag_busybox &
_pull_and_tag_ubuntu_version &
_pull_and_tag_ubuntu_latest
