
services:
  registry:
    image: registry:2
    # ports:
    #   - 443:443
    restart: always
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=https://auth.stevedore.test:5001/auth
      - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
      - REGISTRY_AUTH_TOKEN_ISSUER="stevedore"
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/stevedore.test.crt
      - REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/stevedore.test.crt
      - REGISTRY_HTTP_TLS_KEY=/ssl/stevedore.test.key
    volumes:
      - ./fixtures/ssl:/ssl:ro
    networks:
      default:
        aliases:
          - registry.stevedore.test
          - example.docker.com
    depends_on: 
      - dockerauth
    deploy:
      resources:
        limits:
          memory: 60M
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost","443"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  dockerauth:
    image: cesanta/docker_auth:1
    restart: always
    # ports:
    #   - "5001:5001"
    volumes:
      - ./fixtures/docker_auth:/config:ro
      - ./fixtures/ssl:/ssl:ro
    command: 
      - -logtostderr
      - /config/config.yml
    networks:
      default:
        aliases:
          - auth.stevedore.test
    deploy:
      resources:
        limits:
          memory: 10M
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost","5001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  stevedore:
    build:
      context: ../..
      dockerfile: examples/${EXAMPLE_NAME}/stack/stevedore/Dockerfile
    working_dir: /app/examples/${EXAMPLE_NAME}
    command:
      - tail
      - -f
      - /dev/null
    privileged: true
    environment:
      - GIT_KEYS=/git/keys
      - CGO_ENABLED=0
    volumes:
      - ../..:/app
      - ./fixtures/ssl:/ssl
      - ./fixtures/docker/daemon.json:/etc/docker/daemon.json
    # depends_on:
    #   - gitserver
    deploy:
      resources:
        limits:
          memory: 256M
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost","2376"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
