package image

import (
	"github.com/gostevedore/stevedore/internal/core/domain/builder"
)

// BuildDriverOptions options required by driver to build an image
type BuildDriverOptions struct {
	// AnsibleConnectionLocal is the local connection to use on ansible driver
	AnsibleConnectionLocal bool `yaml:"ansible_connection_local"`
	// AnsibleIntermediateContainerName is the name of an intermediate container that can be used during ansible build process
	AnsibleIntermediateContainerName string `yaml:"ansible_intermediate_container_name"`
	// AnsibleInventoryPath is the path to the ansible inventory file ??
	AnsibleInventoryPath string `yaml:"ansible_inventory_path"`
	// AnsibleLimit is the ansible limit ??
	AnsibleLimit string `yaml:"ansible_limit"`
	// BuilderOptions are those options comming from builder
	BuilderOptions *builder.BuilderOptions `yaml:"builder_options"`
	// BuilderVarMappings are those variables name that will be automatically generated by builder and set to the driver for building the image
	BuilderVarMappings map[string]string `yaml:"builder_variables_mapping"`
	// OutputPrefix prefixes each output line
	OutputPrefix string `yaml:"output_prefix"`
	// PullAuthUsername is the username to use for pulling the image
	PullAuthUsername string `yaml:"pull_auth_username"`
	// PullAuthPassword is the password to use for pulling the image
	PullAuthPassword string `yaml:"pull_auth_password"`
	// PullParentImage indicates whether to pull the parent image
	PullParentImage bool `yaml:"pull_parent_image"`
	// PushAuthUsername is the username to use for pushing the image
	PushAuthUsername string `yaml:"push_auth_username"`
	// PushAuthPassword is the password to use for pushing the image
	PushAuthPassword string `yaml:"push_auth_password"`
	// PushImageAfterBuild flag indicate whether to push the image to the registry once it has been built
	PushImageAfterBuild bool `yaml:"push_image_after_build"`
	// RemoveImageAfterBuild flag indicate whether to remove the image after build
	RemoveImageAfterBuild bool `yaml:"remove_image_after_build"`
}
