---

name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Test:
    strategy:
      matrix:
        os: 
        - ubuntu-latest
        #- macOS-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Run tests 
      run: |
        go test -count=1 -v ./...
