---

name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Test:
    strategy:
      matrix:
        os: 
        - ubuntu-latest
        #- macOS-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - uses: actions/setup-go@v4
      with:
        go-version: '1.19'
        cache-dependency-path: |
          go.sum
          go.sum

    - name: Run unit tests
      run: |
        make unit-test

    - name: Run functional tests
      run: |
        make functional-test
