---

name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

    # That block is not needed anymore because the actions are executed inside a container
    # - uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.19'
    #     cache-dependency-path: |
    #       go.sum
    #       go.sum

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Execute go vet
        run: |
          make vet

  unit-tests:
    runs-on: ubuntu-latest
    needs: static-analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |
          make unit-tests

  functional-tests:
    runs-on: ubuntu-latest
    needs: static-analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run functional tests
        run: |
          make functional-tests
