---

name: ci
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Run tests 
      run: |
        go mod download
        go test -count=1 -cover -v ./...
